In [1]:
import pandas as pd
import numpy as np

In [2]:
olympics = pd.read_csv("../data/raw/athlete_events.csv")
noc_regions = pd.read_csv("../data/raw/noc_regions.csv")

print("Olympic dataset loaded successfully!")
print("NOC regions dataset loaded successfully!")

Olympic dataset loaded successfully!
NOC regions dataset loaded successfully!

In [3]:
print("Olympic dataset shape:", olympics.shape)
print("NOC regions dataset shape:", noc_regions.shape)

Olympic dataset shape: (271116, 15)
NOC regions dataset shape: (230, 3)

In [4]:
print("Olympic dataset columns:")
print(olympics.columns.tolist())

print("\nNOC regions columns:")
print(noc_regions.columns.tolist())

Olympic dataset columns:
['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal']

NOC regions columns:
['NOC', 'region', 'notes']

In [5]:
olympics.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [6]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [7]:
missing_values = olympics.isnull().sum()

print(missing_values)

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [8]:
print("Duplicate rows:", olympics.duplicated().sum())

Duplicate rows: 1385

In [9]:
print("Olympic seasons:")
print(olympics["Season"].value_counts())

Olympic seasons:
Season
Summer    222552
Winter     48564
Name: count, dtype: int64

In [11]:
print("Olympic years:")
print(sorted(olympics["Year"].unique()))
print("\nNumber of records by year:")
print(olympics["Year"].value_counts().sort_index())

Olympic years:
[np.int64(1896), np.int64(1900), np.int64(1904), np.int64(1906), np.int64(1908), np.int64(1912), np.int64(1920), np.int64(1924), np.int64(1928), np.int64(1932), np.int64(1936), np.int64(1948), np.int64(1952), np.int64(1956), np.int64(1960), np.int64(1964), np.int64(1968), np.int64(1972), np.int64(1976), np.int64(1980), np.int64(1984), np.int64(1988), np.int64(1992), np.int64(1994), np.int64(1996), np.int64(1998), np.int64(2000), np.int64(2002), np.int64(2004), np.int64(2006), np.int64(2008), np.int64(2010), np.int64(2012), np.int64(2014), np.int64(2016)]

Number of records by year:
Year
1896      380
1900     1936
1904     1301
1906     1733
1908     3101
1912     4040
1920     4292
1924     5693
1928     5574
1932     3321
1936     7401
1948     7480
1952     9358
1956     6434
1960     9235
1964     9480
1968    10479
1972    11959
1976    10502
1980     8937
1984    11588
1988    14676
1992    16413
1994     3160
1996    13780
1998     3605
2000    13821
2002     4109
2004    13443
2006     4382
2008    13602
2010     4402
2012    12920
2014     4891
2016    13688
Name: count, dtype: int64

In [12]:
print("Medal distribution:")
print(olympics["Medal"].value_counts(dropna=False))

Medal distribution:
Medal
NaN       231333
Gold       13372
Bronze     13295
Silver     13116
Name: count, dtype: int64

In [13]:
print("Number of unique NOC codes:", olympics["NOC"].nunique())
print("Number of unique teams:", olympics["Team"].nunique())
print("Number of unique sports:", olympics["Sport"].nunique())
print("Number of unique events:", olympics["Event"].nunique())

Number of unique NOC codes: 230
Number of unique teams: 1184
Number of unique sports: 66
Number of unique events: 765

In [14]:
year_counts = olympics.groupby(["Year", "Season"]).size().reset_index(name="Records")

print(year_counts.to_string(index=False))

 Year Season  Records
 1896 Summer      380
 1900 Summer     1936
 1904 Summer     1301
 1906 Summer     1733
 1908 Summer     3101
 1912 Summer     4040
 1920 Summer     4292
 1924 Summer     5233
 1924 Winter      460
 1928 Summer     4992
 1928 Winter      582
 1932 Summer     2969
 1932 Winter      352
 1936 Summer     6506
 1936 Winter      895
 1948 Summer     6405
 1948 Winter     1075
 1952 Summer     8270
 1952 Winter     1088
 1956 Summer     5127
 1956 Winter     1307
 1960 Summer     8119
 1960 Winter     1116
 1964 Summer     7702
 1964 Winter     1778
 1968 Summer     8588
 1968 Winter     1891
 1972 Summer    10304
 1972 Winter     1655
 1976 Summer     8641
 1976 Winter     1861
 1980 Summer     7191
 1980 Winter     1746
 1984 Summer     9454
 1984 Winter     2134
 1988 Summer    12037
 1988 Winter     2639
 1992 Summer    12977
 1992 Winter     3436
 1994 Winter     3160
 1996 Summer    13780
 1998 Winter     3605
 2000 Summer    13821
 2002 Winter     4109
 2004 Summer    13443
 2006 Winter     4382
 2008 Summer    13602
 2010 Winter     4402
 2012 Summer    12920
 2014 Winter     4891
 2016 Summer    13688

In [15]:
summer_noc_counts = (
    olympics[olympics["Season"] == "Summer"]
    .groupby("Year")["NOC"]
    .nunique()
    .reset_index(name="Unique_NOCs")
)

print(summer_noc_counts.to_string(index=False))

 Year  Unique_NOCs
 1896           12
 1900           31
 1904           15
 1906           21
 1908           22
 1912           29
 1920           29
 1924           45
 1928           46
 1932           47
 1936           49
 1948           59
 1952           69
 1956           72
 1960           84
 1964           93
 1968          112
 1972          121
 1976           92
 1980           80
 1984          140
 1988          159
 1992          169
 1996          197
 2000          200
 2004          201
 2008          204
 2012          205
 2016          207

In [16]:
summer = olympics[olympics["Season"] == "Summer"].copy()

medal_counts = summer["Medal"].value_counts(dropna=False)

print(medal_counts)

Medal
NaN       188464
Gold       11459
Bronze     11409
Silver     11220
Name: count, dtype: int64

In [17]:
medal_by_noc_year = (
    summer[summer["Medal"].notna()]
    .groupby(["Year", "NOC"])["Medal"]
    .count()
    .reset_index(name="Medal_Records")
)

print(medal_by_noc_year.head(20))

    Year  NOC  Medal_Records
0   1896  AUS              3
1   1896  AUT              5
2   1896  DEN              6
3   1896  FRA             11
4   1896  GBR              9
5   1896  GER             32
6   1896  GRE             48
7   1896  HUN              6
8   1896  SUI              3
9   1896  USA             20
10  1900  AUS              6
11  1900  AUT              6
12  1900  BEL             43
13  1900  BOH              3
14  1900  CAN              2
15  1900  COL              1
16  1900  CUB              2
17  1900  DEN              9
18  1900  ESP              2
19  1900  FRA            235

In [18]:
france_1900 = summer[
    (summer["Year"] == 1900) &
    (summer["NOC"] == "FRA") &
    (summer["Medal"].notna())
]

print(france_1900[["Name", "Sport", "Event", "Medal"]].to_string(index=False))

                                                                  Name         Sport                                                        Event  Medal
                                                        Vladimir Atoff         Rugby                                            Rugby Men's Rugby   Gold
                                                             A. Albert         Rugby                                            Rugby Men's Rugby   Gold
                                                        Auguste Albert       Sailing                                        Sailing Mixed 1-2 Ton Silver
                                                        Auguste Albert       Sailing                                        Sailing Mixed 1-2 Ton Bronze
                                         Richard Louis Pierre Allemane      Football                                      Football Men's Football Silver
                                                             Archenoul Equestrianism                Equestrianism Mixed Hacks And Hunter Combined Silver
                                       William Dunbar "Willie" Attrill       Cricket                                        Cricket Men's Cricket Silver
                             Louis Albert Auguste-Dormeuil (Dormeuil-)       Sailing                                      Sailing Mixed 0.5-1 Ton   Gold
                                         Gaston Achille Louis Aumoitte       Croquet                              Croquet Mixed Singles, One Ball   Gold
                                         Gaston Achille Louis Aumoitte       Croquet                                        Croquet Mixed Doubles   Gold
                                                Albert Jean Louis Ayat       Fencing                      Fencing Men's epee, Masters, Individual   Gold
                                                Albert Jean Louis Ayat       Fencing         Fencing Men's epee, Masters and Amateurs, Individual   Gold
                                                       Louis Dsir Bach      Football                                      Football Men's Football Silver
                                               Hermann Joseph Barrelet        Rowing                                   Rowing Men's Single Sculls   Gold
                                                     Franois "Nol" Bas    Gymnastics                       Gymnastics Men's Individual All-Around Silver
                                                  Denis Raymond Basset    Tug-Of-War                                  Tug-Of-War Men's Tug-Of-War Silver
                                                         Louis Bastien       Cycling                                  Cycling Men's 25 kilometres   Gold
                                                      Jacques Baudrier       Sailing                                      Sailing Mixed 0.5-1 Ton Silver
                                                      Jacques Baudrier       Sailing                                      Sailing Mixed 0.5-1 Ton Bronze
                                                      Jacques Baudrier       Sailing                                        Sailing Mixed 1-2 Ton Bronze
                                             Lucien Alexandre Baudrier       Sailing                                        Sailing Mixed 1-2 Ton Bronze
                                                           J. Bertrand      Swimming                      Swimming Men's 200 metres Team Swimming Silver
                                        Franois Alexandre mile Billard       Sailing                                      Sailing Mixed 10-20 Ton   Gold
                                                           Lon Binoche         Rugby                                            Rugby Men's Rugby   Gold
                                                 Gaston Frdric Blanchy       Sailing                                        Sailing Mixed 2-3 Ton   Gold
                                                 Gaston Frdric Blanchy       Sailing                                        Sailing Mixed 2-3 Ton   Gold
                                                          Alfred Bloch      Football                                      Football Men's Football Silver
                                                 Jules Henri Bouckaert        Rowing                                     Rowing Men's Coxed Fours   Gold
                                                       Gilbert Bougnol       Fencing                      Fencing Men's epee, Masters, Individual Silver
                                 Marcel Jacques Amand Romain Boulenger       Fencing                               Fencing Men's Foil, Individual Bronze
                                            Victor Antoine Jules Cadet      Swimming                      Swimming Men's 200 metres Team Swimming Silver
                                                       Gaston Cailleux       Sailing                                      Sailing Mixed 0-0.5 Ton Bronze
                                                               Camelin    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                  Fernand mile Canelle      Football                                      Football Men's Football Silver
                                                         Andr Castanet     Athletics                           Athletics Men's 5,000 metres, Team Silver
                                       Jean Baptiste Albert Joseph Cau        Rowing                                     Rowing Men's Coxed Fours   Gold
                                             Auguste Baptiste Cavadini      Shooting Shooting Men's Free Rifle, Three Positions, 300 metres, Team Bronze
                                                  mile Julien Champion     Athletics                                     Athletics Men's Marathon Silver
                                            Albert Alphonse Champoudry     Athletics                           Athletics Men's 5,000 metres, Team Silver
                                   Jean-Baptiste tienne August Charcot       Sailing                                      Sailing Mixed 0-0.5 Ton Silver
                                   Jean-Baptiste tienne August Charcot       Sailing                                      Sailing Mixed 0-0.5 Ton Silver
                                                               Charlot        Rowing                                     Rowing Men's Coxed Fours   Gold
                                                         Jean Chastani     Athletics                    Athletics Men's 2,500 metres Steeplechase Bronze
                                                         Jean Chastani     Athletics                           Athletics Men's 5,000 metres, Team Silver
                          Justinien Charles Xavier Clary (Bretonneau-)      Shooting                                          Shooting Men's Trap Bronze
                                                         Jules Clvenot    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                           Jean Collas    Tug-Of-War                                  Tug-Of-War Men's Tug-Of-War Silver
                                                           Jean Collas         Rugby                                            Rugby Men's Rugby   Gold
                                         mile Louis Franois Dsir Coste       Fencing                               Fencing Men's Foil, Individual   Gold
                                                          Eugne Coulon    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                  Auguste Mose Daumain       Cycling                                  Cycling Men's 25 kilometres Bronze
                                      mile Roger de Thomas de Barbarin      Shooting                                          Shooting Men's Trap   Gold
                            Louis Marie Joseph Le Beschu de Champsavin Equestrianism                      Equestrianism Mixed Jumping, Individual Bronze
                                                          de Cottignon       Sailing                                        Sailing Mixed 2-3 Ton Bronze
                              Luc Henri Herv Guy Gardye de la Chapelle        Tennis                                         Tennis Men's Doubles Bronze
                         Louis Verrant Gabriel Le Bailly de la Falaise       Fencing                              Fencing Men's Sabre, Individual   Gold
                            Jean Pierre Marie Joseph  De Madre De Loos          Polo                                              Polo Men's Polo Silver
                                         Robert de Montesquiou-Fzensac Equestrianism                Equestrianism Mixed Hacks And Hunter Combined Bronze
                                  Jean Frdric Andr Poupart de Neuflize Equestrianism                 Equestrianism Mixed Four-In-Hand Competition Bronze
                                                             de Prunel Equestrianism                                Equestrianism Mixed Long Jump Bronze
                                         douard Alphonse de Rothschild          Polo                                              Polo Men's Polo Bronze
Jean lie Louis Octave Guillaume Svre Amanieu Decazes et de Glucksbierg       Sailing                                      Sailing Mixed 10-20 Ton Silver
                                 Maxime Omer Mathieu "Max" Omer-Dcugis        Tennis                                         Tennis Men's Doubles Silver
                                                     Alphonse Decuyper    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                 mile Henri Delchambre        Rowing                                     Rowing Men's Coxed Fours   Gold
                                                 Henry Lon mile Deloge     Athletics                                 Athletics Men's 1,500 metres Silver
                                                 Henry Lon mile Deloge     Athletics                           Athletics Men's 5,000 metres, Team Silver
                                                        Carlos Deltour        Rowing                                     Rowing Men's Coxed Pairs Bronze
                                                 Georges Lucien Dmanet    Gymnastics                       Gymnastics Men's Individual All-Around Bronze
                                                  Charles Devendeville      Swimming                           Swimming Men's Underwater Swimming   Gold
                                       Joseph Augustin "Auguste" Donny       Sailing                                        Sailing Mixed 2-3 Ton Bronze
                                                        Jacques Doucet       Sailing                                        Sailing Mixed 2-3 Ton Silver
                                                        Jacques Doucet       Sailing                                        Sailing Mixed 2-3 Ton Silver
                                                             A. Dubois       Sailing                                       Sailing Mixed 3-10 Ton Bronze
                                                             A. Dubois       Sailing                                       Sailing Mixed 3-10 Ton Silver
                                                             J. Dubois       Sailing                                       Sailing Mixed 3-10 Ton Bronze
                                                             J. Dubois       Sailing                                       Sailing Mixed 3-10 Ton Silver
                                                                Dubosq       Sailing                                        Sailing Mixed 1-2 Ton Bronze
                                                             R. Duparc      Football                                      Football Men's Football Silver
                                            Louis Charles Marie Dutfoy      Shooting                  Shooting Men's Free Pistol, 50 metres, Team Silver
                                                          Albert Duval       Sailing                                        Sailing Mixed 1-2 Ton Silver
                                                          Albert Duval       Sailing                                        Sailing Mixed 1-2 Ton Bronze
                                                                Fardel    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                                Fiolet    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                      mile Lon Fisseux       Archery                      Archery Men's Au Cordon Dore, 50 metres Bronze
                               Mortimer Henri Robert Fournier-Sarlovze          Polo                                              Polo Men's Polo Bronze
                                                 Maurice Eugne Fraysse      Football                                      Football Men's Football Silver
                                             Ren Paul Virgile Gaillard      Football                                      Football Men's Football Silver
                                            Dominique Maximien Gardres Equestrianism                                Equestrianism Mixed High Jump   Gold
                                                       Georges Garnier      Football                                      Football Men's Football Silver
                                                   Charles Andr Gaudin        Rowing                                   Rowing Men's Single Sculls Silver
                                     Henry Jean Guy "Jean-Guy" Gautier         Rugby                                            Rugby Men's Rugby   Gold
                                                                  Gell    Water Polo                                  Water Polo Men's Water Polo Bronze
                                                        Pierre Gervais       Sailing                                      Sailing Mixed 0-0.5 Ton   Gold
                                                        Pierre Gervais       Sailing                                      Sailing Mixed 0-0.5 Ton Bronze
                                         Henri Joseph Marcel Gilardoni       Sailing                                       Sailing Mixed 3-10 Ton   Gold
                                            Auguste Paul Almire Giroux         Rugby                                            Rugby Men's Rugby   Gold
                                                Victor Auguste Godinet       Sailing                                        Sailing Mixed 2-3 Ton Silver
                                                Victor Auguste Godinet       Sailing                                        Sailing Mixed 2-3 Ton Silver
                                  Charles Marius Duma Adolphe Gondouin    Tug-Of-War                                  Tug-Of-War Men's Tug-Of-War Silver
                                  Charles Marius Duma Adolphe Gondouin         Rugby                                            Rugby Men's Rugby   Gold
                                                         Ren Grandjean      Football                                      Football Men's Football Silver
                                                         mile Grumiaux       Archery                    Archery Men's Sur La Perche a La Pyramide   Gold
                                   Henri Napolon Marie Maurice Gufflet       Sailing                                       Sailing Mixed 3-10 Ton Bronze
                                   Henri Napolon Marie Maurice Gufflet       Sailing                                       Sailing Mixed 3-10 Ton Silver
                                                        Robert Gufflet       Sailing                                       Sailing Mixed 3-10 Ton Bronze
                                                        Robert Gufflet       Sailing                                       Sailing Mixed 3-10 Ton Silver
                                                      Charles Guiraist       Sailing                                       Sailing Mixed 3-10 Ton Bronze
                                                      Charles Guiraist       Sailing                                       Sailing Mixed 3-10 Ton Silver
                                  Henri Alphonse Hazebrouck (Charlet-)        Rowing                                     Rowing Men's Coxed Fours   Gold
                                                 Henri Hyacinthe Helle       Archery                         Archery Men's Au Chapelet, 50 metres Silver
                                               Henri Louis Hrouin, Sr.       Archery                      Archery Men's Au Cordon Dore, 50 metres   Gold
                                               Henri Louis Hrouin, Sr.       Archery                           Archery Men's Championnat Du Monde   Gold
                                                             Jean Herv         Rugby                                            Rugby Men's Rugby   Gold
                                               Maurice Louis Hochepied      Swimming                      Swimming Men's 200 metres Team Swimming Silver
                                              Victor Fernand Hochepied      Swimming                      Swimming Men's 200 metres Team Swimming Silver
                                                          Charles Hugo       Sailing                                        Sailing Mixed 1-2 Ton Silver
                                                          Charles Hugo       Sailing                                        Sailing Mixed 1-2 Ton Bronze
                                                Lucien Paul Nol Huteau      Football                                      Football Men's Football Silver
                                                    mile Jean-Fontaine       Sailing                                        Sailing Mixed 2-3 Ton Bronze
                                                  Georges douard Johin       Croquet                              Croquet Mixed Singles, One Ball Silver
                                                  Georges douard Johin       Croquet                                        Croquet Mixed Doubles   Gold
                                            Simon Alphonse Kirchhoffer       Fencing                      Fencing Men's Foil, Masters, Individual Silver
                                                        Marcel Lambert      Football                                      Football Men's Football Silver
                                        Marie Victor Xavier Lardanchet         Rugby                                            Rugby Men's Rugby   Gold
                                               Louis Alexandre Laufray    Water Polo                                  Water Polo Men's Water Polo Bronze
                                          Henri Albert Fernand Laurent       Fencing                      Fencing Men's epee, Masters, Individual Bronze
                                          Gabriel Charles Jean Le Bret       Sailing                                      Sailing Mixed 0.5-1 Ton Silver
                                          Gabriel Charles Jean Le Bret       Sailing                                      Sailing Mixed 0.5-1 Ton Bronze

In [19]:
medal_events = (
    summer[summer["Medal"].notna()]
    [["Year", "NOC", "Event", "Medal"]]
    .drop_duplicates()
)

medal_counts_unique = (
    medal_events
    .groupby(["Year", "NOC"])
    .size()
    .reset_index(name="Medal_Count")
)

print(medal_counts_unique.head(20))

    Year  NOC  Medal_Count
0   1896  AUS            3
1   1896  AUT            5
2   1896  DEN            6
3   1896  FRA           11
4   1896  GBR            9
5   1896  GER           14
6   1896  GRE           44
7   1896  HUN            6
8   1896  SUI            3
9   1896  USA           19
10  1900  AUS            6
11  1900  AUT            6
12  1900  BEL           18
13  1900  BOH            3
14  1900  CAN            2
15  1900  COL            1
16  1900  CUB            2
17  1900  DEN            7
18  1900  ESP            1
19  1900  FRA          102

In [20]:
duplicate_check = (
    summer[summer["Medal"].notna()]
    .groupby(["Year", "NOC", "Event", "Medal"])
    .size()
    .reset_index(name="Athlete_Rows")
)

print(duplicate_check["Athlete_Rows"].value_counts().sort_index())

Athlete_Rows
1     12019
2      1151
3       403
4       811
5       422
6       322
7        69
8       108
9       140
10       26
11       46
12      184
13       50
14       56
15       58
16       81
17       37
18       23
19        6
20       12
22        5
23        1
24       14
25        2
26        2
27        1
28        1
30        1
38        1
Name: count, dtype: int64

In [21]:
print("Number of country-year observations:", len(medal_counts_unique))

print("\nMedal count statistics:")
print(medal_counts_unique["Medal_Count"].describe())

Number of country-year observations: 1275

Medal count statistics:
count    1275.000000
mean       12.589804
std        21.755067
min         1.000000
25%         2.000000
50%         5.000000
75%        14.000000
max       230.000000
Name: Medal_Count, dtype: float64

In [22]:
medal_type_counts = (
    medal_events
    .groupby("Medal")
    .size()
    .reset_index(name="Unique_Medal_Events")
)

print(medal_type_counts)

    Medal  Unique_Medal_Events
0  Bronze                 5600
1    Gold                 5240
2  Silver                 5212

In [23]:
medal_summary = (
    medal_events
    .pivot_table(
        index=["Year", "NOC"],
        columns="Medal",
        values="Event",
        aggfunc="count",
        fill_value=0
    )
    .reset_index()
)

medal_summary["Total_Medals"] = (
    medal_summary["Gold"]
    + medal_summary["Silver"]
    + medal_summary["Bronze"]
)

print(medal_summary.head(20))

Medal  Year  NOC  Bronze  Gold  Silver  Total_Medals
0      1896  AUS       1     2       0             3
1      1896  AUT       2     2       1             5
2      1896  DEN       3     1       2             6
3      1896  FRA       2     5       4            11
4      1896  GBR       3     3       3             9
5      1896  GER       2     7       5            14
6      1896  GRE      17    10      17            44
7      1896  HUN       3     2       1             6
8      1896  SUI       0     1       2             3
9      1896  USA       2    11       6            19
10     1900  AUS       3     3       0             6
11     1900  AUT       3     0       3             6
12     1900  BEL       5     6       7            18
13     1900  BOH       2     0       1             3
14     1900  CAN       1     1       0             2
15     1900  COL       0     0       1             1
16     1900  CUB       0     1       1             2
17     1900  DEN       2     2       3             7
18     1900  ESP       0     1       0             1
19     1900  FRA      34    28      40           102

In [24]:
check_total = (
    medal_summary["Total_Medals"]
    == medal_summary["Gold"]
    + medal_summary["Silver"]
    + medal_summary["Bronze"]
)

print("All medal totals correct:", check_total.all())
print("Number of inconsistent rows:", (~check_total).sum())

All medal totals correct: True
Number of inconsistent rows: 0

In [25]:
id="q3n7xp"
summer_years = sorted(summer["Year"].unique())
summer_nocs = sorted(summer["NOC"].unique())

noc_year_grid = pd.MultiIndex.from_product(
    [summer_years, summer_nocs],
    names=["Year", "NOC"]
).to_frame(index=False)

print("Number of Summer Olympic years:", len(summer_years))
print("Number of NOCs:", len(summer_nocs))
print("Total possible NOC-Year combinations:", len(noc_year_grid))

print("\nFirst 10 rows:")
print(noc_year_grid.head(10))

Number of Summer Olympic years: 29
Number of NOCs: 230
Total possible NOC-Year combinations: 6670

First 10 rows:
   Year  NOC
0  1896  AFG
1  1896  AHO
2  1896  ALB
3  1896  ALG
4  1896  AND
5  1896  ANG
6  1896  ANT
7  1896  ANZ
8  1896  ARG
9  1896  ARM

In [26]:
complete_medal_data = noc_year_grid.merge(
    medal_summary,
    on=["Year", "NOC"],
    how="left"
)

print("Shape:", complete_medal_data.shape)

print("\nMissing values after merge:")
print(complete_medal_data.isna().sum())

print("\nFirst 10 rows:")
print(complete_medal_data.head(10))

Shape: (6670, 6)

Missing values after merge:
Year               0
NOC                0
Bronze          5395
Gold            5395
Silver          5395
Total_Medals    5395
dtype: int64

First 10 rows:
   Year  NOC  Bronze  Gold  Silver  Total_Medals
0  1896  AFG     NaN   NaN     NaN           NaN
1  1896  AHO     NaN   NaN     NaN           NaN
2  1896  ALB     NaN   NaN     NaN           NaN
3  1896  ALG     NaN   NaN     NaN           NaN
4  1896  AND     NaN   NaN     NaN           NaN
5  1896  ANG     NaN   NaN     NaN           NaN
6  1896  ANT     NaN   NaN     NaN           NaN
7  1896  ANZ     NaN   NaN     NaN           NaN
8  1896  ARG     NaN   NaN     NaN           NaN
9  1896  ARM     NaN   NaN     NaN           NaN

In [27]:
participation = (
    summer[["Year", "NOC"]]
    .drop_duplicates()
    .assign(Participated=1)
)

print("Number of actual NOC-Year participation records:", len(participation))

print("\nFirst 20 rows:")
print(participation.head(20))

Number of actual NOC-Year participation records: 2810

First 20 rows:
    Year  NOC  Participated
0   1992  CHN             1
1   2012  CHN             1
2   1920  DEN             1
3   1900  DEN             1
26  1932  NED             1
29  1952  FIN             1
31  2000  FIN             1
32  1996  FIN             1
35  1912  FIN             1
37  1920  FIN             1
39  1924  FIN             1
41  1948  FIN             1
79  2008  NOR             1
80  2016  ROU             1
81  2000  NOR             1
82  2004  NOR             1
86  1920  NOR             1
88  1984  NED             1
89  1968  NOR             1
90  1972  NOR             1

In [28]:
complete_medal_data = complete_medal_data.merge(
    participation,
    on=["Year", "NOC"],
    how="inner"
)

print("Shape after keeping actual participants:", complete_medal_data.shape)

print("\nMissing values:")
print(complete_medal_data.isna().sum())

print("\nFirst 10 rows:")
print(complete_medal_data.head(10))

Shape after keeping actual participants: (2810, 7)

Missing values:
Year               0
NOC                0
Bronze          1535
Gold            1535
Silver          1535
Total_Medals    1535
Participated       0
dtype: int64

First 10 rows:
   Year  NOC  Bronze  Gold  Silver  Total_Medals  Participated
0  1896  AUS     1.0   2.0     0.0           3.0             1
1  1896  AUT     2.0   2.0     1.0           5.0             1
2  1896  DEN     3.0   1.0     2.0           6.0             1
3  1896  FRA     2.0   5.0     4.0          11.0             1
4  1896  GBR     3.0   3.0     3.0           9.0             1
5  1896  GER     2.0   7.0     5.0          14.0             1
6  1896  GRE    17.0  10.0    17.0          44.0             1
7  1896  HUN     3.0   2.0     1.0           6.0             1
8  1896  ITA     NaN   NaN     NaN           NaN             1
9  1896  SUI     0.0   1.0     2.0           3.0             1

In [29]:
medal_columns = ["Bronze", "Gold", "Silver", "Total_Medals"]

complete_medal_data[medal_columns] = (
    complete_medal_data[medal_columns].fillna(0)
)

print("Missing values after filling zero medals:")
print(complete_medal_data.isna().sum())

print("\nSample of zero-medal participants:")
print(
    complete_medal_data[
        complete_medal_data["Total_Medals"] == 0
    ].head(10)
)

Missing values after filling zero medals:
Year            0
NOC             0
Bronze          0
Gold            0
Silver          0
Total_Medals    0
Participated    0
dtype: int64

Sample of zero-medal participants:
    Year  NOC  Bronze  Gold  Silver  Total_Medals  Participated
8   1896  ITA     0.0   0.0     0.0           0.0             1
10  1896  SWE     0.0   0.0     0.0           0.0             1
12  1900  ARG     0.0   0.0     0.0           0.0             1
17  1900  BRA     0.0   0.0     0.0           0.0             1
26  1900  GRE     0.0   0.0     0.0           0.0             1
30  1900  IRI     0.0   0.0     0.0           0.0             1
37  1900  PER     0.0   0.0     0.0           0.0             1
38  1900  ROU     0.0   0.0     0.0           0.0             1
39  1900  RUS     0.0   0.0     0.0           0.0             1
52  1904  ITA     0.0   0.0     0.0           0.0             1

In [30]:
complete_medal_data["Medal_Winner"] = (
    complete_medal_data["Total_Medals"] > 0
).astype(int)

print(complete_medal_data["Medal_Winner"].value_counts())

print("\nMedal winner distribution:")
print(
    complete_medal_data["Medal_Winner"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Medal_Winner
0    1535
1    1275
Name: count, dtype: int64

Medal winner distribution:
Medal_Winner
0    54.63
1    45.37
Name: proportion, dtype: float64

In [31]:
year_target_summary = (
    complete_medal_data
    .groupby("Year")["Medal_Winner"]
    .value_counts()
    .unstack(fill_value=0)
    .rename(columns={0: "No_Medal", 1: "Won_Medal"})
    .reset_index()
)

print(year_target_summary.to_string(index=False))

 Year  No_Medal  Won_Medal
 1896         2         10
 1900         7         24
 1904         3         12
 1906         3         18
 1908         3         19
 1912        10         19
 1920         7         22
 1924        14         31
 1928        12         34
 1932        19         28
 1936        17         32
 1948        21         38
 1952        26         43
 1956        34         38
 1960        40         44
 1964        52         41
 1968        68         44
 1972        73         48
 1976        51         41
 1980        44         36
 1984        93         47
 1988       107         52
 1992       105         64
 1996       118         79
 2000       120         80
 2004       127         74
 2008       118         86
 2012       120         85
 2016       121         86

In [32]:
test_2016 = complete_medal_data[
    complete_medal_data["Year"] == 2016
].copy()

print("2016 observations:", len(test_2016))

print("\n2016 target distribution:")
print(test_2016["Medal_Winner"].value_counts())

print("\n2016 medal statistics:")
print(test_2016["Total_Medals"].describe())

2016 observations: 207

2016 target distribution:
Medal_Winner
0    121
1     86
Name: count, dtype: int64

2016 medal statistics:
count    207.000000
mean       4.700483
std       13.027124
min        0.000000
25%        0.000000
50%        0.000000
75%        3.000000
max      121.000000
Name: Total_Medals, dtype: float64

In [33]:
historical_data = complete_medal_data.sort_values(
    ["NOC", "Year"]
).copy()

historical_data["Previous_Medals"] = (
    historical_data.groupby("NOC")["Total_Medals"].shift(1)
)

print(
    historical_data[
        ["Year", "NOC", "Total_Medals", "Previous_Medals"]
    ].head(20)
)

      Year  NOC  Total_Medals  Previous_Medals
297   1936  AFG           0.0              NaN
346   1948  AFG           0.0              0.0
474   1956  AFG           0.0              0.0
546   1960  AFG           0.0              0.0
630   1964  AFG           0.0              0.0
723   1968  AFG           0.0              0.0
835   1972  AFG           0.0              0.0
1048  1980  AFG           0.0              0.0
1268  1988  AFG           0.0              0.0
1596  1996  AFG           0.0              0.0
1993  2004  AFG           0.0              0.0
2194  2008  AFG           1.0              0.0
2398  2012  AFG           1.0              1.0
2603  2016  AFG           0.0              1.0
405   1952  AHO           0.0              NaN
547   1960  AHO           0.0              0.0
631   1964  AHO           0.0              0.0
724   1968  AHO           0.0              0.0
836   1972  AHO           0.0              0.0
956   1976  AHO           0.0              0.0

In [34]:
print(
    "NOC-Year observations with no previous Olympic record:",
    historical_data["Previous_Medals"].isna().sum()
)

print(
    "NOC-Year observations with previous Olympic record:",
    historical_data["Previous_Medals"].notna().sum()
)

NOC-Year observations with no previous Olympic record: 230
NOC-Year observations with previous Olympic record: 2580

In [35]:
previous_medal_corr = historical_data[
    historical_data["Previous_Medals"].notna()
][["Previous_Medals", "Total_Medals"]].corr()

print(previous_medal_corr)

                 Previous_Medals  Total_Medals
Previous_Medals         1.000000      0.828139
Total_Medals            0.828139      1.000000

In [37]:
test_2016_history = historical_data[
    historical_data["Year"] == 2016
][["NOC", "Previous_Medals"]]

print("2016 NOCs:", len(test_2016_history))
print(
    "2016 NOCs with previous-medal information:",
    test_2016_history["Previous_Medals"].notna().sum()
)
print(
    "2016 NOCs without previous-medal information:",
    test_2016_history["Previous_Medals"].isna().sum()
)

2016 NOCs: 207
2016 NOCs with previous-medal information: 204
2016 NOCs without previous-medal information: 3

In [38]:
historical_data["Previous_2_Medals_Avg"] = (
    historical_data
    .groupby("NOC")["Total_Medals"]
    .transform(
        lambda x: x.shift(1).rolling(window=2, min_periods=1).mean()
    )
)

print(
    historical_data[
        ["Year", "NOC", "Total_Medals",
         "Previous_Medals", "Previous_2_Medals_Avg"]
    ].head(20)
)

      Year  NOC  Total_Medals  Previous_Medals  Previous_2_Medals_Avg
297   1936  AFG           0.0              NaN                    NaN
346   1948  AFG           0.0              0.0                    0.0
474   1956  AFG           0.0              0.0                    0.0
546   1960  AFG           0.0              0.0                    0.0
630   1964  AFG           0.0              0.0                    0.0
723   1968  AFG           0.0              0.0                    0.0
835   1972  AFG           0.0              0.0                    0.0
1048  1980  AFG           0.0              0.0                    0.0
1268  1988  AFG           0.0              0.0                    0.0
1596  1996  AFG           0.0              0.0                    0.0
1993  2004  AFG           0.0              0.0                    0.0
2194  2008  AFG           1.0              0.0                    0.0
2398  2012  AFG           1.0              1.0                    0.5
2603  2016  AFG           0.0              1.0                    1.0
405   1952  AHO           0.0              NaN                    NaN
547   1960  AHO           0.0              0.0                    0.0
631   1964  AHO           0.0              0.0                    0.0
724   1968  AHO           0.0              0.0                    0.0
836   1972  AHO           0.0              0.0                    0.0
956   1976  AHO           0.0              0.0                    0.0

In [39]:
test_2016_history = historical_data[
    historical_data["Year"] == 2016
][
    ["NOC", "Previous_Medals", "Previous_2_Medals_Avg"]
]

print("2016 observations:", len(test_2016_history))

print(
    "Previous_Medals available:",
    test_2016_history["Previous_Medals"].notna().sum()
)

print(
    "Previous_2_Medals_Avg available:",
    test_2016_history["Previous_2_Medals_Avg"].notna().sum()
)

print("\nMissing values:")
print(test_2016_history.isna().sum())

2016 observations: 207
Previous_Medals available: 204
Previous_2_Medals_Avg available: 204

Missing values:
NOC                      0
Previous_Medals          3
Previous_2_Medals_Avg    3
dtype: int64

In [40]:
noc_mapping_check = noc_regions[
    ["NOC", "region"]
].drop_duplicates()

print("Unique NOCs in mapping file:", noc_mapping_check["NOC"].nunique())

print("\nMissing region names:")
print(noc_mapping_check["region"].isna().sum())

print("\nSample mapping:")
print(noc_mapping_check.head(15))

Unique NOCs in mapping file: 230

Missing region names:
3

Sample mapping:
    NOC          region
0   AFG     Afghanistan
1   AHO         Curacao
2   ALB         Albania
3   ALG         Algeria
4   AND         Andorra
5   ANG          Angola
6   ANT         Antigua
7   ANZ       Australia
8   ARG       Argentina
9   ARM         Armenia
10  ARU           Aruba
11  ASA  American Samoa
12  AUS       Australia
13  AUT         Austria
14  AZE      Azerbaijan

In [41]:
missing_noc_regions = noc_mapping_check[
    noc_mapping_check["region"].isna()
]

print(missing_noc_regions)

     NOC region
168  ROT    NaN
208  TUV    NaN
213  UNK    NaN

In [42]:
# Create a clean NOC-to-country mapping
noc_country_map = (
    noc_regions[["NOC", "region"]]
    .drop_duplicates()
    .rename(columns={"region": "Country"})
)

print("NOC-country mapping shape:", noc_country_map.shape)
print("\nMissing country names:")
print(noc_country_map[noc_country_map["Country"].isna()])

print("\nSample mapping:")
print(noc_country_map.head(15))

NOC-country mapping shape: (230, 2)

Missing country names:
     NOC Country
168  ROT     NaN
208  TUV     NaN
213  UNK     NaN

Sample mapping:
    NOC         Country
0   AFG     Afghanistan
1   AHO         Curacao
2   ALB         Albania
3   ALG         Algeria
4   AND         Andorra
5   ANG          Angola
6   ANT         Antigua
7   ANZ       Australia
8   ARG       Argentina
9   ARM         Armenia
10  ARU           Aruba
11  ASA  American Samoa
12  AUS       Australia
13  AUT         Austria
14  AZE      Azerbaijan

In [43]:
import requests

# Olympic years used for our modeling period
olympic_years = [1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016]

# World Bank indicator codes
indicators = {
    "GDP_per_capita": "NY.GDP.PCAP.CD",
    "Population": "SP.POP.TOTL",
    "Life_Expectancy": "SP.DYN.LE00.IN"
}

wdi_frames = []

for indicator_name, indicator_code in indicators.items():
    url = (
        f"https://api.worldbank.org/v2/country/all/indicator/"
        f"{indicator_code}"
        f"?date=1988:2016&format=json&per_page=20000"
    )

    response = requests.get(url)

    print(f"{indicator_name} - Status code:", response.status_code)

    data = response.json()[1]

    df = pd.DataFrame(data)

    df = df[["countryiso3code", "date", "value"]].copy()

    df["Year"] = df["date"].astype(int)
    df["NOC_WDI_Code"] = df["countryiso3code"]

    df = df[df["Year"].isin(olympic_years)]

    df = df.rename(columns={"value": indicator_name})

    df = df[["NOC_WDI_Code", "Year", indicator_name]]

    wdi_frames.append(df)

wdi_data = wdi_frames[0]

for df in wdi_frames[1:]:
    wdi_data = wdi_data.merge(
        df,
        on=["NOC_WDI_Code", "Year"],
        how="outer"
    )

print("\nWDI data shape:", wdi_data.shape)
print("\nColumns:")
print(wdi_data.columns.tolist())

print("\nSample:")
print(wdi_data.head(15))

GDP_per_capita - Status code: 200
Population - Status code: 200
Life_Expectancy - Status code: 200

WDI data shape: (3080, 5)

Columns:
['NOC_WDI_Code', 'Year', 'GDP_per_capita', 'Population', 'Life_Expectancy']

Sample:
   NOC_WDI_Code  Year  GDP_per_capita    Population  Life_Expectancy
0                1988    14461.032409  1.166528e+09        74.213601
1                1988    14461.032409  1.166528e+09        49.571454
2                1988    14461.032409  1.166528e+09        57.016354
3                1988    14461.032409  1.166528e+09              NaN
4                1988    14461.032409  1.166528e+09        66.767528
5                1988    14461.032409  2.740377e+08        74.213601
6                1988    14461.032409  2.740377e+08        49.571454
7                1988    14461.032409  2.740377e+08        57.016354
8                1988    14461.032409  2.740377e+08              NaN
9                1988    14461.032409  2.740377e+08        66.767528
10               1988    14461.032409  1.510077e+09        74.213601
11               1988    14461.032409  1.510077e+09        49.571454
12               1988    14461.032409  1.510077e+09        57.016354
13               1988    14461.032409  1.510077e+09              NaN
14               1988    14461.032409  1.510077e+09        66.767528

In [45]:
# Fetch World Development Indicators correctly

olympic_years = [1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016]

indicators = {
    "GDP_per_capita": "NY.GDP.PCAP.CD",
    "Population": "SP.POP.TOTL",
    "Life_Expectancy": "SP.DYN.LE00.IN"
}

wdi_frames = []

for indicator_name, indicator_code in indicators.items():

    all_records = []

    # Fetch all pages from the World Bank API
    first_url = (
        f"https://api.worldbank.org/v2/country/all/indicator/"
        f"{indicator_code}"
        f"?date=1988:2016&format=json&per_page=1000&page=1"
    )

    first_response = requests.get(first_url)
    first_json = first_response.json()

    total_pages = first_json[0]["pages"]

    all_records.extend(first_json[1])

    for page in range(2, total_pages + 1):
        url = (
            f"https://api.worldbank.org/v2/country/all/indicator/"
            f"{indicator_code}"
            f"?date=1988:2016&format=json&per_page=1000&page={page}"
        )

        response = requests.get(url)
        page_data = response.json()

        if len(page_data) > 1:
            all_records.extend(page_data[1])

    df = pd.DataFrame(all_records)

    # Keep only the required fields
    df = df[
        ["countryiso3code", "date", "value"]
    ].copy()

    df["Year"] = df["date"].astype(int)

    # Keep only Olympic years
    df = df[df["Year"].isin(olympic_years)]

    df = df.rename(
        columns={
            "countryiso3code": "WDI_Code",
            "value": indicator_name
        }
    )

    df = df[
        ["WDI_Code", "Year", indicator_name]
    ]

    wdi_frames.append(df)

    print(
        indicator_name,
        "records:",
        len(df)
    )

# Merge the three indicators
wdi_data = wdi_frames[0]

for df in wdi_frames[1:]:
    wdi_data = wdi_data.merge(
        df,
        on=["WDI_Code", "Year"],
        how="outer"
    )

print("\nFinal WDI shape:", wdi_data.shape)

print("\nColumns:")
print(wdi_data.columns.tolist())

print("\nSample:")
print(wdi_data.head(15))

GDP_per_capita records: 2120
Population records: 2120
Life_Expectancy records: 2120

Final WDI shape: (3080, 5)

Columns:
['WDI_Code', 'Year', 'GDP_per_capita', 'Population', 'Life_Expectancy']

Sample:
   WDI_Code  Year  GDP_per_capita    Population  Life_Expectancy
0            1988    14461.032409  1.166528e+09        74.213601
1            1988    14461.032409  1.166528e+09        49.571454
2            1988    14461.032409  1.166528e+09        57.016354
3            1988    14461.032409  1.166528e+09              NaN
4            1988    14461.032409  1.166528e+09        66.767528
5            1988    14461.032409  2.740377e+08        74.213601
6            1988    14461.032409  2.740377e+08        49.571454
7            1988    14461.032409  2.740377e+08        57.016354
8            1988    14461.032409  2.740377e+08              NaN
9            1988    14461.032409  2.740377e+08        66.767528
10           1988    14461.032409  1.510077e+09        74.213601
11           1988    14461.032409  1.510077e+09        49.571454
12           1988    14461.032409  1.510077e+09        57.016354
13           1988    14461.032409  1.510077e+09              NaN
14           1988    14461.032409  1.510077e+09        66.767528

In [46]:
print("Number of non-missing WDI codes:",
      wdi_data["WDI_Code"].notna().sum())

print("\nNumber of unique WDI codes:",
      wdi_data["WDI_Code"].nunique())

print("\nFirst 20 unique WDI codes:")
print(wdi_data["WDI_Code"].dropna().unique()[:20])

print("\nNumber of blank WDI codes:")
print((wdi_data["WDI_Code"] == "").sum())

Number of non-missing WDI codes: 3080

Number of unique WDI codes: 261

First 20 unique WDI codes:
<StringArray>
[   '', 'ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG',
 'ARM', 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN']
Length: 20, dtype: str

Number of blank WDI codes:
1000

In [47]:
# Remove records without a valid World Bank country code

wdi_data_clean = wdi_data[
    wdi_data["WDI_Code"].notna()
    & (wdi_data["WDI_Code"] != "")
].copy()

print("Original WDI shape:", wdi_data.shape)
print("After removing blank codes:", wdi_data_clean.shape)

print("\nNumber of unique WDI codes:",
      wdi_data_clean["WDI_Code"].nunique())

print("\nFirst 20 WDI codes:")
print(wdi_data_clean["WDI_Code"].unique()[:20])

print("\nSample:")
print(wdi_data_clean.head(15))

Original WDI shape: (3080, 5)
After removing blank codes: (2080, 5)

Number of unique WDI codes: 260

First 20 WDI codes:
<StringArray>
['ABW', 'AFE', 'AFG', 'AFW', 'AGO', 'ALB', 'AND', 'ARB', 'ARE', 'ARG', 'ARM',
 'ASM', 'ATG', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA']
Length: 20, dtype: str

Sample:
     WDI_Code  Year  GDP_per_capita   Population  Life_Expectancy
1000      ABW  1988    10056.261393      59331.0        72.519000
1001      ABW  1992    13892.605143      69005.0        72.717000
1002      ABW  1996    16620.954556      83021.0        72.856000
1003      ABW  2000    20681.023027      90588.0        72.939000
1004      ABW  2004    23700.631990      95138.0        73.223000
1005      ABW  2008    28171.909401     100917.0        73.783000
1006      ABW  2012    25119.665545     104110.0        74.841000
1007      ABW  2016    27441.550214     108727.0        75.540000
1008      AFE  1988      704.143241  294498625.0        50.876607
1009      AFE  1992      732.912139  329082707.0        50.715946
1010      AFE  1996      746.788581  366138524.0        51.353190
1011      AFE  2000      706.728441  406156661.0        52.557342
1012      AFE  2004      989.017115  450928044.0        54.192928
1013      AFE  2008     1447.427775  502070763.0        57.240106
1014      AFE  2012     1731.869096  559609961.0        60.249512

In [48]:
# Identify WDI codes that are not directly represented by Olympic NOCs

olympic_noc_codes = set(noc_country_map["NOC"])

wdi_codes = set(wdi_data_clean["WDI_Code"])

non_olympic_codes = sorted(wdi_codes - olympic_noc_codes)

print("Number of WDI codes not matching Olympic NOCs:",
      len(non_olympic_codes))

print("\nFirst 50 non-matching codes:")
print(non_olympic_codes[:50])

Number of WDI codes not matching Olympic NOCs: 139

First 50 non-matching codes:
['ABW', 'AFE', 'AFW', 'AGO', 'ARB', 'ARE', 'ASM', 'ATG', 'BFA', 'BGD', 'BGR', 'BHR', 'BHS', 'BLZ', 'BMU', 'BRB', 'BTN', 'BWA', 'CEB', 'CHE', 'CHL', 'COG', 'CRI', 'CSS', 'CUW', 'CYM', 'DEU', 'DNK', 'DZA', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'FJI', 'FRO', 'GIB', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC', 'GRD', 'GRL', 'GTM', 'HND', 'HPC', 'HRV']

In [49]:
# Check how many Olympic NOCs directly match World Bank ISO-3 codes

olympic_nocs = set(noc_country_map["NOC"].dropna())
wdi_codes = set(wdi_data_clean["WDI_Code"].dropna())

direct_matches = sorted(olympic_nocs & wdi_codes)
no_direct_match = sorted(olympic_nocs - wdi_codes)

print("Olympic NOCs:", len(olympic_nocs))
print("Direct WDI matches:", len(direct_matches))
print("Olympic NOCs without direct WDI match:", len(no_direct_match))

print("\nFirst 30 direct matches:")
print(direct_matches[:30])

print("\nOlympic NOCs without direct WDI match:")
print(no_direct_match)

Olympic NOCs: 230
Direct WDI matches: 121
Olympic NOCs without direct WDI match: 109

First 30 direct matches:
['AFG', 'ALB', 'AND', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BIH', 'BLR', 'BOL', 'BRA', 'BRN', 'CAF', 'CAN', 'CHI', 'CHN', 'CIV', 'CMR', 'COD', 'COL', 'COM', 'CPV', 'CUB', 'CYP', 'CZE', 'DJI']

Olympic NOCs without direct WDI match:
['AHO', 'ALG', 'ANG', 'ANT', 'ANZ', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOH', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'CRT', 'DEN', 'ESA', 'EUN', 'FIJ', 'FRG', 'GAM', 'GBS', 'GDR', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IOA', 'IRI', 'ISV', 'IVB', 'KOS', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAL', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NBO', 'NCA', 'NED', 'NEP', 'NFL', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'RHO', 'ROT', 'RSA', 'SAA', 'SAM', 'SCG', 'SEY', 'SIN', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TCH', 'TGA', 'TOG', 'TPE', 'UAE', 'UAR', 'UNK', 'URS', 'URU', 'VAN', 'VIE', 'VIN', 'WIF', 'YAR', 'YMD', 'YUG', 'ZAM', 'ZIM']

In [51]:
# NOCs actually appearing in our modeling period (1988-2016)

modeling_period_data = complete_medal_data[
    complete_medal_data["Year"].between(1988, 2016)
].copy()

modeling_nocs = sorted(
    modeling_period_data["NOC"].dropna().unique()
)

modeling_noc_set = set(modeling_nocs)

unmatched_modeling_nocs = sorted(
    modeling_noc_set - wdi_codes
)

print("NOCs appearing in 1988-2016:", len(modeling_nocs))
print("Directly matched to WDI:", 
      len(modeling_noc_set & wdi_codes))
print("Unmatched NOCs needing mapping:",
      len(unmatched_modeling_nocs))

print("\nUnmatched NOCs in 1988-2016:")
print(unmatched_modeling_nocs)

NOCs appearing in 1988-2016: 218
Directly matched to WDI: 121
Unmatched NOCs needing mapping: 97

Unmatched NOCs in 1988-2016:
['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'EUN', 'FIJ', 'FRG', 'GAM', 'GBS', 'GDR', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IOA', 'IRI', 'ISV', 'IVB', 'KOS', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'ROT', 'RSA', 'SAM', 'SCG', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TCH', 'TGA', 'TOG', 'TPE', 'UAE', 'URS', 'URU', 'VAN', 'VIE', 'VIN', 'YAR', 'YMD', 'YUG', 'ZAM', 'ZIM']

In [54]:
# Check unmatched NOCs by Olympic year

unmatched_by_year = (
    modeling_period_data[
        modeling_period_data["NOC"].isin(unmatched_modeling_nocs)
    ]
    .groupby("Year")["NOC"]
    .nunique()
    .reset_index(name="Unmatched_NOC_Count")
)

print(unmatched_by_year)

print("\nUnmatched NOCs appearing in each Olympic year:")

for year in sorted(modeling_period_data["Year"].unique()):
    year_nocs = set(
        modeling_period_data[
            modeling_period_data["Year"] == year
        ]["NOC"]
    )

    unmatched = sorted(year_nocs & set(unmatched_modeling_nocs))

    print(f"{year}: {unmatched}")

   Year  Unmatched_NOC_Count
0  1988                   79
1  1992                   83
2  1996                   86
3  2000                   87
4  2004                   86
5  2008                   84
6  2012                   85
7  2016                   86

Unmatched NOCs appearing in each Olympic year:
1988: ['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BUL', 'BUR', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'DEN', 'ESA', 'FIJ', 'FRG', 'GAM', 'GDR', 'GEQ', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LBA', 'LES', 'LIB', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'POR', 'PUR', 'SAM', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TCH', 'TGA', 'TOG', 'TPE', 'UAE', 'URS', 'URU', 'VAN', 'VIE', 'VIN', 'YAR', 'YMD', 'YUG', 'ZAM', 'ZIM']
1992: ['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BUL', 'BUR', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'EUN', 'FIJ', 'GAM', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IOA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'POR', 'PUR', 'RSA', 'SAM', 'SEY', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TCH', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']
1996: ['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'FIJ', 'GAM', 'GBS', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'RSA', 'SAM', 'SCG', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']
2000: ['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'FIJ', 'GAM', 'GBS', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IOA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'RSA', 'SAM', 'SCG', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']
2004: ['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'FIJ', 'GAM', 'GBS', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'RSA', 'SAM', 'SCG', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']
2008: ['AHO', 'ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'FIJ', 'GAM', 'GBS', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'RSA', 'SAM', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']
2012: ['ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'FIJ', 'GAM', 'GBS', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IOA', 'IRI', 'ISV', 'IVB', 'KSA', 'KUW', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'RSA', 'SAM', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']
2016: ['ALG', 'ANG', 'ANT', 'ARU', 'ASA', 'BAH', 'BAN', 'BAR', 'BER', 'BHU', 'BIZ', 'BOT', 'BRU', 'BUL', 'BUR', 'CAM', 'CAY', 'CGO', 'CHA', 'COK', 'CRC', 'CRO', 'DEN', 'ESA', 'FIJ', 'GAM', 'GBS', 'GEQ', 'GER', 'GRE', 'GRN', 'GUA', 'GUI', 'HAI', 'HON', 'INA', 'IOA', 'IRI', 'ISV', 'IVB', 'KOS', 'KSA', 'LAT', 'LBA', 'LES', 'LIB', 'MAD', 'MAS', 'MAW', 'MGL', 'MON', 'MRI', 'MTN', 'MYA', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'OMA', 'PAR', 'PHI', 'PLE', 'POR', 'PUR', 'ROT', 'RSA', 'SAM', 'SEY', 'SKN', 'SLO', 'SOL', 'SRI', 'SUD', 'SUI', 'TAN', 'TGA', 'TOG', 'TPE', 'UAE', 'URU', 'VAN', 'VIE', 'VIN', 'ZAM', 'ZIM']